export const SCANNER_EVENTS = {
  WINNOWING_STARTING: 'WINNOWING_STARTING',
  WINNOWING_NEW_WFP_FILE: 'WINNOWING_NEW_WFP_FILE',
  WINNOWING_FINISHED: 'WINNOWING_FINISHED',

  DISPATCHER_WFP_SENDED: 'DATA_DISPATCHED',
  DISPATCHER_NEW_DATA: 'NEW_DATA',
  DISPATCHER_FINISHED: 'DISPATCHER_FINISHED',

  SCAN_DONE: 'SCAN_DONE',

  ERROR_SCANNER_ABORTED: 'ERROR_SCANNER_ABORTED',

};
