export const ScannerEvents = {
  WINNOWING_STARTING: 'WINNOWING_STARTING',
  WINNOWING_NEW_WFP_FILE: 'WINNOWING_NEW_WFP_FILE',
  WINNOWING_NEW_CONTENT: 'WINNOWING_NEW_CONTENT',
  WINNOWING_FINISHED: 'WINNOWING_FINISHED',

  DISPATCHER_WFP_SENDED: 'DISPATCHER_WFP_SENDED',
  DISPATCHER_NEW_DATA: 'DISPATCHER_NEW_DATA',
  DISPATCHER_FINISHED: 'DISPATCHER_FINISHED',
  DISPATCHER_ITEM_NO_DISPATCHED: 'DISPATCHER_ITEM_NO_DISPATCHED',
  DISPATCHER_QUEUE_SIZE_MAX_LIMIT: 'DISPATCHER_QUEUE_FULL',
  DISPATCHER_QUEUE_SIZE_MIN_LIMIT: 'DISPATCHER_QUEUE_SIZE_MIN_LIMIT',

  ERROR_SCANNER_ABORTED: 'ERROR_SCANNER_ABORTED',

  ERROR_SERVER_SIDE: 'ERROR_SERVER_SIDE',
  ERROR_CLIENT_SIDE: 'ERROR_CLIENT_SIDE',

  MODULE_DISPATCHER: 'MODULE_DISPATCHER',
  MODULE_WINNOWER: 'MODULE_WINNOWER',

  SCAN_DONE: 'SCAN_DONE',
  RESULTS_APPENDED: 'RESULTS_APPENDED',
};
