export const DispatcherEvents = {
  DONE: 'DONE',

  ERROR_NETWORK_CONNECTIVITY: 'NETWORK_CONNECTIVITY',
  ERROR_TRANSACTION_TIMEOUT: 'TimeoutError',

  STATUS_RUNNING: 'STATUS_RUNNING',
  STATUS_ERROR: 'STATUS_ERROR',
};
