export enum IpcEvents {
  SCANNER_INIT_SCAN = 'SCANNER_INIT_SCAN',
  SCANNER_FINISH_SCAN = 'SCANNER_FINISH_SCAN',

  INVENTORY_CREATE = 'INVENTORY_CREATE',
  INVENTORY_GET = 'INVENTORY_GET',
  INVENTORY_DELETE = 'INVENTORY_DELETE',

  COMPONENT_CREATE = 'COMPONENT_CREATE',
  COMPONENT_DELETE = 'COMPONENT_DELETE',
  COMPONENT_GET = 'COMPONENT_GET',

  LICENSE_CREATE = 'LICENSE_CREATE',
  LICENSE_GET = 'LICENSE_GET',
  LICENSE_DELETE = 'LICENSE_DELETE',
  LICENSE_ATTACH = 'LICENSE_ATTACH',

  ITEM_INCLUDE = 'ITEM_INCLUDE',
  ITEM_EXCLUDE = 'ITEM_EXCLUDE',

  FILTER_ADD = 'FILTER_ADD',
  FILTER_DELETE = 'FILTER_DELETE',
}

export const ipcMainEvents = [IpcEvents.SCANNER_FINISH_SCAN];

export const ipcRendererEvents = [
  IpcEvents.SCANNER_INIT_SCAN,

  IpcEvents.INVENTORY_CREATE,
  IpcEvents.INVENTORY_GET,
  IpcEvents.INVENTORY_DELETE,

  IpcEvents.COMPONENT_CREATE,
  IpcEvents.COMPONENT_DELETE,
  IpcEvents.COMPONENT_GET,

  IpcEvents.LICENSE_CREATE,
  IpcEvents.LICENSE_GET,
  IpcEvents.LICENSE_DELETE,
  IpcEvents.LICENSE_ATTACH,

  IpcEvents.ITEM_INCLUDE,
  IpcEvents.ITEM_EXCLUDE,

  IpcEvents.FILTER_ADD,
  IpcEvents.FILTER_DELETE,
];
